---
abstract: 'PSGI server with built-in HTTPS support, Unix sockets, preforking'
author:
  - 'Steven Haryanto <stevenharyanto@gmail.com>'
build_requires:
  Module::Build: 0.3601
configure_requires:
  Module::Build: 0.3601
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300002, CPAN::Meta::Converter version 2.112150'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Gepok
requires:
  Class::XSAccessor: 0
  File::HomeDir: 0
  HTTP::Daemon: 0
  HTTP::Daemon::SSL: 0
  HTTP::Daemon::UNIX: 0.03
  HTTP::Date: 0
  HTTP::Status: 0
  IO::Scalar: 0
  Log::Any: 0
  Moo: 0
  Plack: 0
  SHARYANTO::Proc::Daemon::Prefork: 0.05
  Test::More: 0.96
  URI::Escape: 0
  perl: 5.010000
resources:
  homepage: http://search.cpan.org/dist/Gepok/
  repository: http://github.com/sharyanto/perl-Gepok
version: 0.17
